name: ai_recipe
description: "Transform your cooking with personalized, AI-generated recipes tailored to your tastes and ingredients"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  async: ^2.11.0
  camera: ^0.10.5+9
  cloud_firestore: ^4.15.7
  device_info_plus: ^9.1.2
  firebase_core: ^2.26.0
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  flutter_markdown: ^0.6.20
  flutter_svg: ^2.0.9
  google_fonts: 6.1.0
  google_generative_ai: ^0.4.0
  image_picker: ^1.0.7
  material_symbols_icons: ^4.2741.0
  path: ^1.9.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  analysis_defaults:
#    path: ../analysis_defaults

flutter:
  uses-material-design: true

  assets:
    - assets/